### ISSUE TITLE
Use another port besides 80

### ISSUE THREAD

**Issue by orientalsniper** [pipech/erpnext-docker-debian#1]
Sorry, I don't see a conversation/discussion tab, how do I change the port? I tried editing the config.v2.json of the nginx container, but it gets recreated. I'm using stable.

**Comment by pipech** [comment]
Hi,

May I ask why you want to change port?

I haven't tried yet but I think you should tried change [nginx.conf](https://github.com/pipech/erpnext-docker-debian/blob/master/production_setup/conf/nginx-conf/nginx.conf)

```
server {
        listen 80;
```

and [prd.yml](https://github.com/pipech/erpnext-docker-debian/blob/master/production_setup/prd.yml)

```
  nginx:
    image: nginx:1.12.2
    deploy:
      replicas: 1
    configs:
      - source: nginx-conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
```

Hope this helps. :)
