### ISSUE TITLE
Installation Questions

### ISSUE THREAD

**Issue by Olawale1** [pipech/erpnext-docker-debian#19]
Hi @pipech 

How do I start a new setup? I tried stopping the containers using `docker stop $(docker ps -a -q)` but it appears they got restarted automatically

Thanks

**Comment by pipech** [comment]
run `docker stack rm your_stack_name`

Documentation on docker stack is here
https://docs.docker.com/engine/reference/commandline/stack_rm

**Comment by Olawale1** [comment]
Hi @pipech 

I was able to complete the installation successfully this time around :))

There is however still one issue; some other domains pointing to other websites on the same server are now showing a "404 page not found" error. How can we resolve this please?

Kind regards,

**Comment by Olawale1** [comment]
Hi @pipech 

The 404 error on the other domains occurs once I deploy the stack. I'm guessing this has to do with either Traefik or Nginx settings but not sure which and how to get around it...

Thanks

**Comment by pipech** [comment]
Hi @Olawale1 

Do you mean that you have another docker container running another web server on the same host ?
If that is the case you have to config traefik to point incoming traffic to that container.

```
  frappe:
    image: pipech/erpnext-docker-debian:stable
    deploy:
      replicas: 1
    ports:
      - "8000:8000"   #webserver_port
      - "9000:9000"   #socketio_port
      - "6787:6787"   #file_watcher_port
    volumes:
      - frappe-sites-volumes:/home/frappe/bench/sites
      - frappe-logs-volumes:/home/frappe/bench/logs
    stdin_open: true
    tty: true
    env_file:
      - ./env/frappe_app.env
    command: ["/home/frappe/production_config/entrypoint_prd.sh"]
    labels:
      - "traefik.enable=true"
      # - "traefik.frontend.rule=Host:t01.spacecode.co.th, t02.spacecode.co.th" [Separate with comma]
      - "traefik.frontend.rule=Host:t01.spacecode.co.th"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
      - default
```

You could try to replicate frappe config to your container (labels and networks parts) 
More information about Traefik are here https://docs.traefik.io
