### ISSUE TITLE
Question: Traefik instead of nginx for reverse proxy smart?

### ISSUE THREAD

**Issue by garyritchie** [pipech/erpnext-docker-debian#5]
I'm currently evaluating deployment patterns for ERPNext and found your repo. Is there something about Frappe/bench that might prevent me from trying to switch to Traefik for rev proxy? The intent is to run additional low-use containers to the same host/instance for more efficient resource utilization.

Edit: Short answer is yes, but I'm still investigating if there will be any side-affects...

```yaml
version: '3.3'

networks:
  proxy:
    external:
      name: proxy

services:

  traefik:
    image: traefik
    command: --api --web --docker --docker.watch --docker.domain=localhost --logLevel=DEBUG
    networks:
      - proxy
    ports:
      # - "80:80"     # The HTTP port
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  nginx-frappe:
    image: nginx:1.12.2
    environment:
      - VIRTUAL_HOST=frappe.localhost
    networks:
      - proxy
      - default
    volumes:
      - ./conf/nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - frappe-sites-volumes:/home/frappe/bench/sites
      - frappe-apps-volumes:/home/frappe/bench/apps
    labels:
      - "traefik.backend=frappe"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:frappe.docker.localhost"
      - "traefik.port=80"
      - "traefik.protocol=http"

  mariadb:
    image: mariadb:10.2.12
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123
    networks:
      - default
    volumes:
      - ./conf/mariadb-conf/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
      - ./conf/mariadb-conf/init.sql:/home/init.sql
      - mariadb-data-volumes:/var/lib/mysql
    ports:
      - "3307:3306"

  redis-cache:
    image: redis:alpine
    networks:
      - default
    volumes:
      - ./conf/redis-conf/redis_cache.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  redis-queue:
    image: redis:alpine
    networks:
      - default
    volumes:
      - ./conf/redis-conf/redis_queue.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  redis-socketio:
    image: redis:alpine
    networks:
      - default
    volumes:
      - ./conf/redis-conf/redis_socketio.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  frappe:
    image: pipech/erpnext-docker-debian-production:stable
    environment:
    # beware prdsite1.local has been hardcoded into nginx-conf/nginx.conf
      - benchNewSiteName=prdsite1.local
    networks:
      - proxy
      - default
    # ports:
    #   - "8000:8000"   #webserver_port
    #   - "9000:9000"   #socketio_port
    #   - "6787:6787"   #file_watcher_port
    expose:
      - "8000"
      - "9000"
      - "6787"
    volumes:
      - ./conf/frappe-docker-conf/init.sh:/home/frappe/init.sh
      - frappe-sites-volumes:/home/frappe/bench/sites
      - frappe-apps-volumes:/home/frappe/bench/apps
      - frappe-logs-volumes:/home/frappe/bench/logs
    stdin_open: true
    tty: true
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

  portainer:
    image: portainer/portainer
    restart: unless-stopped
    networks:
      - default
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.frontend.rule=Host:portainer.docker.localhost"
      - "traefik.port=9000"
      - "traefik.backend=portainer"
      - "traefik.docker.network=proxy"

volumes:
  frappe-sites-volumes:
  frappe-apps-volumes:
  frappe-logs-volumes:
  mariadb-data-volumes:
```

My primary reason for doing this is to be able to test "production" configuration prior to deployment... and Traefik has made me lazy in this respect.
