### ISSUE TITLE
Recommendation for changing Administrator account

### ISSUE THREAD

**Issue by garyritchie** [pipech/erpnext-docker-debian#77]
Using production_setup instructions and there doesn't seem to be a way to set a different password, _more permanently_ for the Administrator, found in production_setup/conf/frappe-docker-conf/common_site_config_docker.json.

In frappe.yml I've tried using config:
```yaml
configs:
  frappe-commonsite-conf:
    file: ./conf/frappe-docker-conf/common_site_config_docker.json
...
configs:
  frappe-commonsite-conf:
    file: ./conf/frappe-docker-conf/common_site_config_docker.json
```
or volume:
```yaml
volumes:
      - frappe-sites-volumes:/home/frappe/bench/sites
      - frappe-logs-volumes:/home/frappe/bench/logs
      - ./conf/frappe-docker-conf:/home/frappe/production_config
```

Neither method overwrites the `common_site_config.json`. I know I can adjust the Dockerfile, but I wanted to make sure there wasn't an easier method.
